plugins:
#定义了一个带过期缓存的内部使用/外部使用的国外dns服务器
#转发dns请求到国外dns
  - tag: foreign
    type: aliapi
    args:
      concurrent: 2
      upstreams:
        - addr: "https://1.1.1.1/dns-query"
          socks5: ""
        - addr: "https://8.8.8.8/dns-query"
          socks5: ""
          upstream_query_timeout: 1000

#国内域名 内部使用
  - tag: sequence_google_in
    type: sequence
    args:
      - matches: switch4 'A'
        exec: $cache_google
      - exec: flow_setter sequence=sequence_google_in upstream=foreign
      - exec: $foreign
      - exec: cname_remover

#国外
  - tag: udp_google
    type: udp_server
    args:
      entry: sequence_google_in
      listen: ":3333"

  - tag: tcp_google
    type: tcp_server
    args:
      entry: sequence_google_in
      listen: ":3333"

#定义了一个带过期缓存的内部使用/外部使用的国外dns服务器（带ecs），供节点域名解析使用
#在不泄露版本中，供不在域名列表中的域名初次解析使用
  - tag: foreignecs
    type: aliapi
    args:
      concurrent: 1
      upstreams:
        - addr: "https://8.8.8.8/dns-query"
          socks5: "127.0.0.1:7891"

  - tag: sequence_google_ecs
    type: sequence
    args:
      - exec: ecs 2408:8888::8
      - exec: $cache_google_ecs
      - exec: flow_setter sequence=sequence_google_ecs upstream=foreignecs
      - exec: $foreignecs
      - exec: cname_remover

  - tag: sequence_google_nocache
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_google_nocache upstream=foreign
      - exec: $foreign
      - exec: cname_remover

  - tag: udp_google_ecs
    type: udp_server
    args:
      entry: sequence_google_ecs
      listen: ":4444"

  - tag: tcp_google_ecs
    type: tcp_server
    args:
      entry: sequence_google_ecs
      listen: ":4444"