plugins:
#使用前面定义的内部dns服务器，并定义可复用的序列，文件名中的1代表了层级
#转发请求至sing-box/mihome dns请求fakeip
  - tag: nocnfake
    type: aliapi
    args:
      concurrent: 1
      upstreams:
        - addr: "udp://127.0.0.1:7874"

#向mihomo请求国内的fakeip
  - tag: cnfake
    type: aliapi
    args:
      concurrent: 1
      upstreams:
        - addr: "udp://127.0.0.1:1053"

#缓存序列-国内域名realip
  - tag: sequence_local_exit
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_local_exit upstream=domestic
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cn                             #定义: sub_config/cache.yaml:27
      - exec: $domestic                             #定义: sub_config/forward_local.yaml:3
      - exec: cname_remover
      - exec: exit

  - tag: sequence_local_exit_requery
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_local_exit_requery upstream=domestic
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cn                             #定义: sub_config/cache.yaml:27
      - exec: $domestic                             #定义: sub_config/forward_local.yaml:3
      - exec: cname_remover
      - matches:
        - qtype 1                                   #A请求
        - "!resp_ip 0.0.0.0/0"
        exec:
          - flow_setter sequence=sequence_local_exit_requery upstream=foreign
          - $foreign                                #定义: sub_config/forward_nocn.yaml:4
      - matches:
        - qtype 1                                   #A请求
        - "!resp_ip 0.0.0.0/0"
        exec: $my_nov4list                          #定义: sub_config/domain_output.yaml:69
      - matches:
        - qtype 28                                  #AAAA请求
        - "!resp_ip 2000::/3"
        exec: $my_nov6list                          #定义: sub_config/domain_output.yaml:54
      - exec: exit

#缓存序列-国内域名realip
  - tag: sequence_local_addlist_exit
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_local_addlist_exit upstream=domestic
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cn                             #定义: sub_config/cache.yaml:27
      - exec: $domestic                             #定义: sub_config/forward_local.yaml:3
      - exec: cname_remover
      - matches: "!fast_mark 11"                    #不在记忆直连和特殊域名列表中
        exec: $my_realiplist                        #加入自生成国内域名列表；定义: sub_config/domain_output.yaml:25
      - exec: exit

  - tag: sequence_local_addlist_exit_v6
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_local_addlist_exit_v6 upstream=domestic
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cn                             #定义: sub_config/cache.yaml:27
      - exec: $domestic                             #定义: sub_config/forward_local.yaml:3
      - exec: cname_remover
      - matches: "!fast_mark 11"                    #不在记忆直连和特殊域名列表中
        exec: $my_realiplist                        #加入自生成国内域名列表；定义: sub_config/domain_output.yaml:25
      - matches:
        - "!fast_mark 3"                            #不在无V6清单中
        - "!resp_ip 2000::/3"
        exec: $my_nov6list                          #定义: sub_config/domain_output.yaml:54
      - exec: exit

  - tag: sequence_local_addlist_exit_requery
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_local_addlist_exit_requery upstream=domestic
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cn                             #定义: sub_config/cache.yaml:27
      - exec: $domestic                             #定义: sub_config/forward_local.yaml:3
      - exec: cname_remover
      - matches:
        - qtype 28                                  #AAAA请求
        - "!resp_ip 2000::/3"
        exec: $my_nov6list                          #定义: sub_config/domain_output.yaml:54
      - matches:
        - qtype 1                                   #A请求
        - "!resp_ip 0.0.0.0/0"
        exec: fast_mark 19
      - matches: fast_mark 19
        exec:
          - flow_setter sequence=sequence_local_addlist_exit_requery upstream=foreign
          - $foreign                                #定义: sub_config/forward_nocn.yaml:4
      - matches:
        - qtype 1                                   #A请求
        - "!resp_ip 0.0.0.0/0"
        exec: $my_nov4list                          #定义: sub_config/domain_output.yaml:69
      - matches:
        - fast_mark 19                              #A请求
        - "resp_ip 0.0.0.0/0"                       #有IP
        - "!resp_ip $geoip_cn"                      #但是没有cn ip
        exec:
          - $my_fakeiplist
          - $my_sv4list
          - drop_resp
          - flow_setter sequence=sequence_local_addlist_exit_requery upstream=nocnfake
          - $nocnfake
          - exit
      - matches: "!fast_mark 11"                    #不在记忆直连和特殊域名列表中
        exec: $my_realiplist                        #加入自生成国内域名列表；定义: sub_config/domain_output.yaml:25
      - exec: exit

  - tag: sequence_local
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_local upstream=domestic
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cn                             #定义: sub_config/cache.yaml:27
      - exec: $domestic                             #定义: sub_config/forward_local.yaml:3
      - exec: cname_remover


#仅加入清单并结束整个查询
  - tag: sequence_addrealiplist_exit
    type: sequence
    args:
      - matches: "!fast_mark 11"                    #不在记忆直连和特殊域名列表中
        exec: $my_realiplist                        #加入自生成国内域名列表；定义: sub_config/domain_output.yaml:25
      - exec: exit

#向mihomo请求国内的fakeip序列，重新向国内dns请求
  - tag: sequence_local_fake
    type: sequence
    args:
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cnmihomo                       #定义: sub_config/cache.yaml:63
      - matches: fast_mark 10
        exec:
          - $sequence_local                         #定义: sub_config/forward_1.yaml:112
          - flow_setter sequence=sequence_local_fake upstream=domestic
      - matches: "!fast_mark 10"
        exec:
          - flow_setter sequence=sequence_local_fake upstream=cnfake
          - $cnfake                                 #定义: sub_config/forward_1.yaml:12
      - exec: ttl 5

  - tag: sequence_local_fake_clashmi
    type: sequence
    args:
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cnmihomo                       #定义: sub_config/cache.yaml:63
      - matches: fast_mark 10
        exec:
          - $sequence_local                         #定义: sub_config/forward_1.yaml:112
          - flow_setter sequence=sequence_local_fake_clashmi upstream=domestic
      - matches: "!fast_mark 10"
        exec:
          - flow_setter sequence=sequence_local_fake_clashmi upstream=cnfake
          - $cnfake                                 #定义: sub_config/forward_1.yaml:12
      - exec: ttl 5

#向mihomo请求国内的fakeip序列并缓存
  - tag: sequence_local_fake_pure
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_local_fake_pure upstream=cnfake
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cnmihomo                       #定义: sub_config/cache.yaml:63
      - exec: $cnfake                               #定义: sub_config/forward_1.yaml:12
      - exec: ttl 5

#向mihomo请求国内的fakeip序列、加入清单并结束
  - tag: sequence_localfake_addlist_exit
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_localfake_addlist_exit upstream=cnfake
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cnmihomo                       #定义: sub_config/cache.yaml:63
      - exec: $cnfake                               #定义: sub_config/forward_1.yaml:12
      - exec: ttl 5
      - matches: "!fast_mark 11"                    #不在记忆直连和特殊域名列表中
        exec: $my_realiplist                        #加入自生成国内域名列表；定义: sub_config/domain_output.yaml:25
      - exec: exit

  - tag: sequence_localfake_addlist_exit_requery
    type: sequence
    args:
      - exec: $domestic                             #定义: sub_config/forward_local.yaml:3
      - exec: cname_remover
      - matches:
        - qtype 28                                  #AAAA请求
        - "!resp_ip 2000::/3"
        exec: $my_nov6list                          #定义: sub_config/domain_output.yaml:54
      - matches:
        - qtype 1                                   #A请求
        - "!resp_ip 0.0.0.0/0"
        exec: fast_mark 19
      - matches: fast_mark 19
        exec:
          - flow_setter sequence=sequence_localfake_addlist_exit_requery upstream=foreign
          - $foreign                                #定义: sub_config/forward_nocn.yaml:4
      - matches:
        - qtype 1                                   #A请求
        - "!resp_ip 0.0.0.0/0"
        exec: $my_nov4list                          #定义: sub_config/domain_output.yaml:69
      - matches:
        - fast_mark 19                              #A请求
        - "resp_ip 0.0.0.0/0"                       #有IP
        - "!resp_ip $geoip_cn"                      #但是没有cn ip
        exec:
          - $my_fakeiplist
          - $my_sv4list
          - drop_resp
          - flow_setter sequence=sequence_localfake_addlist_exit_requery upstream=nocnfake
          - $nocnfake
          - exit
      - exec: drop_resp
      - exec: flow_setter sequence=sequence_localfake_addlist_exit_requery upstream=cnfake
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cnmihomo                       #定义: sub_config/cache.yaml:63
      - exec: $cnfake                               #定义: sub_config/forward_1.yaml:12
      - exec: ttl 5
      - matches: "!fast_mark 11"                    #不在记忆直连和特殊域名列表中
        exec: $my_realiplist                        #加入自生成国内域名列表；定义: sub_config/domain_output.yaml:25
      - exec: exit

#向mihomo请求国内的fakeip序列并结束
  - tag: sequence_localfake_exit
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_localfake_exit upstream=cnfake
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cnmihomo                       #定义: sub_config/cache.yaml:63
      - exec: $cnfake                               #定义: sub_config/forward_1.yaml:12
      - exec: ttl 5
      - exec: exit

  - tag: sequence_localfake_exit_requery
    type: sequence
    args:
      - exec: $domestic                             #定义: sub_config/forward_local.yaml:3
      - exec: cname_remover
      - matches:
        - qtype 1                                   #A请求
        - "!resp_ip 0.0.0.0/0"
        exec:
          - flow_setter sequence=sequence_localfake_exit_requery upstream=foreign
          - $foreign                                #定义: sub_config/forward_nocn.yaml:4
      - matches:
        - qtype 1                                   #A请求
        - "!resp_ip 0.0.0.0/0"
        exec: $my_nov4list                          #定义: sub_config/domain_output.yaml:69
      - matches:
        - qtype 28                                  #AAAA请求
        - "!resp_ip 2000::/3"
        exec: $my_nov6list                          #定义: sub_config/domain_output.yaml:54
      - exec: drop_resp
      - exec: flow_setter sequence=sequence_localfake_exit_requery upstream=cnfake
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_cnmihomo                       #定义: sub_config/cache.yaml:63
      - exec: $cnfake                               #定义: sub_config/forward_1.yaml:12
      - exec: ttl 5
      - exec: exit

#缓存序列-列表外域名
  - tag: sequence_google
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_google upstream=foreign
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_google                         #定义: sub_config/cache.yaml:36
      - exec: $foreign                              #定义: sub_config/forward_nocn.yaml:4
      - exec: cname_remover

#缓存序列-列表外域名
  - tag: sequence_google_exit
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_google_exit upstream=foreign
      - matches: switch4 'A'                        #定义: sub_config/switch.yaml:35
        exec: $cache_google                         #定义: sub_config/cache.yaml:36
      - exec: $foreign                              #定义: sub_config/forward_nocn.yaml:4
      - exec: cname_remover
      - exec: exit

#FakeIP 分流：代理域名返回 FakeIP，并加入记忆代理清单
  - tag: sequence_proxy_fakeip_addlist_exit
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_proxy_fakeip_addlist_exit upstream=nocnfake
      - exec: $nocnfake                             #定义: sub_config/forward_1.yaml:4
      - matches: "!fast_mark 12"
        exec: $my_fakeiplist                        #继续作为记忆代理域名列表
      - exec: exit

#FakeIP 分流：代理域名返回 FakeIP
  - tag: sequence_proxy_fakeip_exit
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_proxy_fakeip_exit upstream=nocnfake
      - exec: $nocnfake                             #定义: sub_config/forward_1.yaml:4
      - exec: exit

#RealIP 分流：代理域名返回国外真实 IP，并加入记忆代理清单
  - tag: sequence_proxy_realip_addlist_exit
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_proxy_realip_addlist_exit upstream=foreign
      - exec: $foreign
      - exec: cname_remover
      - matches: "!fast_mark 12"
        exec: $my_fakeiplist                        #继续作为记忆代理域名列表
      - exec: exit

#RealIP 分流：代理域名返回国外真实 IP
  - tag: sequence_proxy_realip_exit
    type: sequence
    args:
      - exec: flow_setter sequence=sequence_proxy_realip_exit upstream=foreign
      - exec: $foreign
      - exec: cname_remover
      - exec: exit

#代理域名响应入口：根据 DNS 分流模式返回 FakeIP 或 RealIP，并加入记忆代理清单后结束
  - tag: sequence_fakeip_addlist_exit
    type: sequence
    args:
      - matches: switch17 'A'
        exec: $sequence_proxy_fakeip_addlist_exit
      - matches: switch17 'B'
        exec: $sequence_proxy_realip_addlist_exit
      - exec: exit

#代理域名响应入口：根据 DNS 分流模式返回 FakeIP 或 RealIP 后结束
  - tag: sequence_fakeip_exit
    type: sequence
    args:
      - matches: switch17 'A'
        exec: $sequence_proxy_fakeip_exit
      - matches: switch17 'B'
        exec: $sequence_proxy_realip_exit
      - exec: exit

#国内域名 内部使用
  - tag: sequence_local_in
    type: sequence
    args:
      - exec: $sequence_local                       #定义: sub_config/forward_1.yaml:112
      - exec: flow_setter sequence=sequence_local_in upstream=domestic

#优先国外realip，失败则回退国内，不带缓存
  - tag: "prefer_foreign_nocache"
    type: "fallback"
    args:
      primary: foreign                                  # 主可执行插件的 tag
      secondary: domestic                          # 副可执行插件的 tag
      threshold: 1000                                       # 无响应回滚阈值。单位毫秒。默认 500 。
      always_standby: false                            # 副可执行插件始终待命。 


#国内
  - tag: udp_local
    type: udp_server
    args:
      entry: sequence_local_in
      listen: ":2222"

  - tag: tcp_local
    type: tcp_server
    args:
      entry: sequence_local_in
      listen: ":2222"
